### ISSUE TITLE
.config/file.ext

### ISSUE THREAD

**Issue by shannonmoeller** [cowboy/node-findup-sync#17]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), but I'm also submitting issues to the `findup`, `karma`, `travis-ci` and `zuul` repos.

**Comment by jonschlinkert** [comment]
hey @shannonmoeller! so I assume you're posing this here to get support for the concept?

**Comment by shannonmoeller** [comment]
Partly. Even if npm never adopts the pattern, as the core module behind many CLIs, `findup-sync` could facilitate this pattern for many other common utilities.

**Comment by shannonmoeller** [comment]
@jonschlinkert Basically, I'm recommending that the `.config/` directory be added to the list of default locations to check for configuration files. The idea here is to foster the use of [http://standards.freedesktop.org/basedir-spec/latest/index.html](http://standards.freedesktop.org/basedir-spec/latest/index.html) where `$HOME` is a module's root directory to [declutter](http://unix.stackexchange.com/a/38871) module repos.

So the search would look like this where X is the current directory:

1. If X/file.ext exists, load it. STOP
2. If X/.config/file.ext exists, load it. STOP
3. Change X to parent directory. GO TO 1

Some modules allow the path to be configured in package.json, but that's replacing file noise with config noise and requires additional effort in every project. By allowing this change in `node-findup-sync`, many of the most-used Node.js-based CLIs would inherit the feature automatically.

**Comment by jonschlinkert** [comment]
> Awesome to see that you're the guy behind the rewrite. Nice work.

thanks! very kind of you to say. yeah fwiw I didn't want it merged yet b/c I found a bug in micromatch. I believe I fixed that issue a week or so ago, but I want to get [this other stuff taken care of](https://github.com/jonschlinkert/micromatch/issues/27) before merging.

> recommending that the .config/ directory be added to the list of default locations to check for configuration files

I've always liked the idea of a `.config/` directory, seems like a worthwhile goal. let me know if I can help

**Comment by shannonmoeller** [comment]
Awesome. Would you be open to a PR that adds an option to enable checking in `.config` dirs when finding?

**Comment by jonschlinkert** [comment]
Honestly, I need to think about it first, and even then would probably want feedback from @tkellen or @cowboy. I'm a big advocate of innovation and trying new things, but with a project that's so heavily used every seemingly trivial change is a calculated risk. 

Fwiw, I'm in favor of the concept from an absolute sense, but IMHO it seems like it would be more effective to start with jshint, jslint, travis, etc, and try to get them to officially support it. Then it's just a matter of implementors adding support. Please let me know if I'm just missing the point - wouldn't be the first time

**Comment by jonschlinkert** [comment]
so, a few other thoughts... 

1. I have this image in my mind of projects with 40 dotfiles in the `.config/` directory of a project, "just because". But then again, who cares? especially if the convention is to have npm ignore it (or not include it). 
2. Some kind of windows issues we've never thought of
3. more windows issues that won't be resolved when number 2 is fixed
4. it might be fun to write a lib specifically to do the resolving for this... have you thought of doing one?

**Comment by shannonmoeller** [comment]
Agreed. Small changes can escalate to big ones very quickly. That's why I thought it would be good to have it as an option rather than the default behavior.

I specifically (and selfishly) targeted this module because it is used by grunt, gulp, and liftoff which I used on a daily basis. I have already submitted this exact same request to jshint, jshint, eslint, karma, travis-ci, and others.

1. If I need 40 config files for all the tools being used on a project, I'd absolutely prefer them to be in a sub directory rather than in the root of my project. Oy!

2. Granted.

3. Absolutely granted. :)

4. That would make a good test case, and I probably will, but for reasons mentioned above this is the module I really care about.

**Comment by cowboy** [comment]
Doesn't it make more sense for the tool that uses this lib to do `findup('{.config/,}foo.js')` to match `foo.js` or `.config/foo.js`?

**Comment by jonschlinkert** [comment]
> findup('{.config/,}foo.js') to match foo.js or .config/foo.js?

yeah, agreed. that's what I was trying to say here:

> Then it's just a matter of implementors adding support.

point of clarification though. @shannonmoeller, when you said:

> Basically, I'm recommending that the .config/ directory be added to the list of default locations to check for configuration files. 

I was assuming you meant "I'm recommending" in an absolute sense, that you were asking if we would follow the convention in this project, like the other issues you created for other projects, not that you wanted to add a feature to findup-sync. is that right?

**Comment by shannonmoeller** [comment]
I was making a feature request. I honestly didn't realize that findup went both up and down. So, yeah. It's on the implementers to add support. Finding a lot more resistance there though.

Many thanks.

**Comment by jonschlinkert** [comment]
> Finding a lot more resistance there though.

well, that's to be expected. that's why I was suggesting you make a lib, so instead of pushing a "convention" that makes people have to think too much. Instead, depending on how the code is written in other libs, you could (ideally) just do prs that introduce minimal changes.  

You write great code though, so even if the changes are big, just ask them if they'd consider a pr. IMHO this is a more digestible way to present the idea to maintainers. But that's only my perspective

**Comment by tkellen** [comment]
For posterity, my thoughts here: gulpjs/gulp#1054

**Comment by shannonmoeller** [comment]
@tkellen With respect, my [counter points](https://github.com/gulpjs/gulp/issues/1054) are now there as well.

**Comment by shannonmoeller** [comment]
@jonschlinkert @tkellen Thanks for the advice to take a PR approach. [Kicking the tires](https://www.npmjs.com/package/find-config).

**Comment by jonschlinkert** [comment]
@shannonmoeller the `lookup` function seems like it's pretty close to the code in my pr, does `findup` not work for that use case? or were you waiting for the pr to be merged?

**Comment by shannonmoeller** [comment]
Waiting for PR. Wanted to document and write tests for what I have in mind. Wanted to run some perf tests to see what omitting glob and nocase support could do. Wanted a module I can modify with which to start prototyping forks.

**Comment by jonschlinkert** [comment]
sounds good, thanks.

**Comment by shannonmoeller** [comment]
> or were you waiting for the pr to be merged

Anything I can do to help out?

**Comment by jonschlinkert** [comment]
with the micromatch stuff? no I'm just about finished with it. I think the docs were the only thing left. thanks though
