### ISSUE TITLE
Update dependency on glob to 5.x to fix network file lookups

### ISSUE THREAD

**Issue by jsheely** [cowboy/node-findup-sync#20]
See also:
https://github.com/isaacs/node-glob/issues/205
https://github.com/projectkudu/kudu/issues/1573
https://github.com/gulpjs/gulp/issues/1251

**Comment by phated** [comment]
@jsheely what were the breaking changes that caused 4.x -> 5.x, need to make sure that they don't effect dependents.

**Comment by tkellen** [comment]
Updated and bumped to `0.3.0`. With so many dependents there is absolutely no way I'd publish this as a patch release. People will have to opt in on this one. That said, we should probably be @ `1.0` at this point. I'm not making that decision for @cowboy, though.

**Comment by phated** [comment]
:+1: to bumping v0.3.0 to 1.0
